const fs = require('fs');
let text = fs.readFileSync('index.html', 'utf8');

const replacements = [
    ['A\uFFFD\'ADIDAS', 'AÑADIDAS'],
    ['REDISE\uFFFD\'O', 'REDISEÑO'],
    ['ESC\uFFFD\?NER', 'ESCÁNER'],
    ['P\uFFFD\?GINA', 'PÁGINA'],
    ['SECCI\uFFFD\"N', 'SECCIÓN'],
    ['T\uFFFDs ERES', 'TÚ ERES'],
    ['DUE\uFFFD\'O', 'DUEÑO'],
    ['CU\uFFFD\?NTO', '¿CUÁNTO'],
    ['ESTAR\uFFFD\?', 'ESTARÁ'],
    ['DESPU\uFFFD%S', 'DESPUÉS'],
    ['QU\uFFFD%', 'QUÉ'],
    ['TECNOLOG\uFFFD\?AS', 'TECNOLOGÍAS'],
    ['COTIZACI\uFFFD\"N', 'COTIZACIÓN'],
    ['ELECTR\uFFFD\"NICO', 'ELECTRÓNICO'],
    ['TEL\uFFFD%FONO', 'TELÉFONO'],
    ['PAR\uFFFD\?METROS', 'PARÁMETROS'],
    ['LIBRER\uFFFD\?AS', 'LIBRERÍAS'],
    ['L\uFFFD\"GICA', 'LÓGICA'],
    ['ANIMACI\uFFFD\"N', 'ANIMACIÓN'],
    ['INICIALIZACI\uFFFD\"N', 'INICIALIZACIÓN'],
    ['PART\uFFFD\?CULAS', 'PARTÍCULAS'],
    ['DIN\uFFFD\?MICA', 'DINÁMICA'],
    ['\uFFFDY\"\" NUEVA', '✅ NUEVA'],
    ['TRANSACCI\uFFFD\"N', 'TRANSACCIÓN'],
    ['BOT\uFFFD\"N', 'BOTÓN'],
    ['L\uFFFD\?NEA', 'LÍNEA'],
    ['INVERSI\uFFFD\"N', 'INVERSIÓN'],
    ['NAVEGACI\uFFFD\"N', 'NAVEGACIÓN'],
    ['men\uFFFDs', 'menús'],
    ['trav\uFFFDs', 'través'],
    ['c\uFFFDdigo', 'código'],
    ['dise\uFFFDo', 'diseño'],
    ['Falc\uFFFDn', 'Falcón'],
    ['t\uFFFDtulo', 'título'],
    ['secci\uFFFDn', 'sección'],
    ['Separaci\uFFFDn', 'Separación'],
    ['Tama\uFFFDo', 'Tamaño'],
    ['ne\uFFFDn', 'neón'],
    ['mayor\uFFFDa', 'mayoría'],
    ['acci\uFFFDn', 'acción'],
    ['Bot\uFFFDn', 'Botón'],
    ['Est\uFFFD', 'Está'],
    ['m\uFFFDs', 'más'],
    ['m\uFFFDvil', 'móvil'],
    ['Olv\uFFFDdate', 'Olvídate'],
    ['dise\uFFFDadas', 'diseñadas'],
    ['m\uFFFDximo', 'máximo'],
    ['estr\uFFFDs', 'estrés'],
    ['tecnol\uFFFDgico', 'tecnológico'],
    ['gastron\uFFFDmico', 'gastronómico'],
    ['Suscripci\uFFFDn', 'Suscripción'],
    ['conversi\uFFFDn', 'conversión'],
    ['campa\uFFFDas', 'campañas'],
    ['men\uFFFD', 'menú'],
    ['entrar\uFFFDn', 'entrarán'],
    ['aqu\uFFFD', 'aquí'],
    ['t\uFFFDcnica', 'técnica'],
    ['S\uFFFD', 'Sí'],
    ['producci\uFFFDn', 'producción'],
    ['a\uFFFDo', 'año'],
    ['ultrarr\uFFFDpido', 'ultrarrápido'],
    ['t\uFFFD ', 'tú '],
    ['r\uFFFDpida', 'rápida'],
    ['tr\uFFFDfico', 'tráfico'],
    ['b\uFFFDsico', 'básico'],
    ['d\uFFFD', 'dé'],
    ['Peque\uFFFDo', 'Pequeño'],
    ['conexi\uFFFDn', 'conexión'],
    ['Env\uFFFDo', 'Envío'],
    ['enviar\uFFFD', 'enviará'],
    ['cu\uFFFDnto', 'cuánto'],
    ['d\uFFFDnde', 'dónde'],
    ['m\uFFFDgicamente', 'mágicamente']
];

for (const [bad, good] of replacements) {
    text = text.split(bad).join(good);
}

fs.writeFileSync('index.html', text, 'utf8');
