const fs = require('fs');
let text = fs.readFileSync('index.html', 'utf8');

const map = {
    'A\uFFFD\'ADIDAS': 'AÑADIDAS',
    'REDISE\uFFFD\'O': 'REDISEÑO',
    'ESC\uFFFD\?NER': 'ESCÁNER',
    'P\uFFFD\?GINA': 'PÁGINA',
    'SECCI\uFFFD\"N': 'SECCIÓN',
    'T\uFFFDs': 'TÚ',
    'DUE\uFFFD\'O': 'DUEÑO',
    'CU\uFFFD\?NTO': '¿CUÁNTO',
    'ESTAR\uFFFD\?': 'ESTARÁ',
    'DESPU\uFFFD%S': 'DESPUÉS',
    'QU\uFFFD%': 'QUÉ',
    'TECNOLOG\uFFFD\?AS': 'TECNOLOGÍAS',
    'COTIZACI\uFFFD\"N': 'COTIZACIÓN',
    'ELECTR\uFFFD\"NICO': 'ELECTRÓNICO',
    'TEL\uFFFD%FONO': 'TELÉFONO',
    'PAR\uFFFD\?METROS': 'PARÁMETROS',
    'LIBRER\uFFFD\?AS': 'LIBRERÍAS',
    'L\uFFFD\"GICA': 'LÓGICA',
    'ANIMACI\uFFFD\"N': 'ANIMACIÓN',
    'INICIALIZACI\uFFFD\"N': 'INICIALIZACIÓN',
    'PART\uFFFD\?CULAS': 'PARTÍCULAS',
    'DIN\uFFFD\?MICA': 'DINÁMICA',
    '\uFFFDY\"\" NUEVA': '✅ NUEVA',
    'TRANSACCI\uFFFD\"N': 'TRANSACCIÓN',
    'BOT\uFFFD\"N': 'BOTÓN',
    'L\uFFFD\?NEA': 'LÍNEA',
    'INVERSI\uFFFD\"N': 'INVERSIÓN',
    'NAVEGACI\uFFFD\"N': 'NAVEGACIÓN',
    'men\uFFFDs': 'menús',
    'trav\uFFFDs': 'través',
    'c\uFFFDdigo': 'código',
    'dise\uFFFDo': 'diseño',
    'Falc\uFFFDn': 'Falcón',
    't\uFFFDtulo': 'título',
    'secci\uFFFDn': 'sección',
    'Separaci\uFFFDn': 'Separación',
    'Tama\uFFFDo': 'Tamaño',
    'ne\uFFFDn': 'neón',
    'mayor\uFFFDa': 'mayoría',
    'acci\uFFFDn': 'acción',
    'Bot\uFFFDn': 'Botón',
    'Est\uFFFD': 'Está',
    'm\uFFFDs': 'más',
    'm\uFFFDvil': 'móvil',
    'Olv\uFFFDdate': 'Olvídate',
    'dise\uFFFDadas': 'diseñadas',
    'm\uFFFDximo': 'máximo',
    'estr\uFFFDs': 'estrés',
    'tecnol\uFFFDgico': 'tecnológico',
    'gastron\uFFFDmico': 'gastronómico',
    'Suscripci\uFFFDn': 'Suscripción',
    'conversi\uFFFDn': 'conversión',
    'campa\uFFFDas': 'campañas',
    'men\uFFFD': 'menú',
    'entrar\uFFFDn': 'entrarán',
    'aqu\uFFFD': 'aquí',
    't\uFFFDcnica': 'técnica',
    'S\uFFFD': 'Sí',
    'producci\uFFFDn': 'producción',
    'a\uFFFDo': 'año',
    'ultrarr\uFFFDpido': 'ultrarrápido',
    't\uFFFD ': 'tú ',
    'r\uFFFDpida': 'rápida',
    'tr\uFFFDfico': 'tráfico',
    'b\uFFFDsico': 'básico',
    'd\uFFFD': 'dé',
    'Peque\uFFFDo': 'Pequeño',
    'conexi\uFFFDn': 'conexión',
    'Env\uFFFDo': 'Envío',
    'enviar\uFFFD': 'enviará',
    'cu\uFFFDnto': 'cuánto',
    'd\uFFFDnde': 'dónde',
    'm\uFFFDgicamente': 'mágicamente',
    'a\uFFFD\uFFFD\'\uFFFD\'\uFFFDn': 'aún',
    'L\uFFFD\"GICA': 'LÓGICA',
    '\uFFFDaccent\uFFFDcyan': '--accent-cyan',
    '\uFFFDaccent\uFFFDorange': '--accent-orange',
    'bento\uFFFDcontainer': 'bento-container',
    'contact\uFFFDmodal\uFFFDoverlay': 'contact-modal-overlay',
    'open\uFFFDmodal\uFFFDbtn': 'open-modal-btn',
    'close\uFFFDmodal\uFFFDbtn': 'close-modal-btn',
    'bento\uFFFDitem': 'bento-item',
    'bento\uFFFDtooltip': 'bento-tooltip',
    'font\uFFFDsize': 'font-size',
    'contact\uFFFDform': 'contact-form',
    'form\uFFFDname': 'form-name',
    'form\uFFFDemail': 'form-email',
    'form\uFFFDphone': 'form-phone',
    'form\uFFFDmessage': 'form-message',
    'submit\uFFFDbtn': 'submit-btn',
    'Content\uFFFDType': 'Content-Type',
    'service\uFFFDrow': 'service-row'
};

for (const [bad, good] of Object.entries(map)) {
    text = text.split(bad).join(good);
}

// Any remaining  should probably be a hyphen
text = text.replace(/\uFFFD/g, '-');

fs.writeFileSync('index.html', text, 'utf8');
